# Generated by Django 5.1.3 on 2024-11-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='cidade',
            field=models.TextField(max_length=100),
        ),
    ]
