# Generated by Django 5.1.3 on 2024-11-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_alter_instituicao_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
    ]
